version: '2'
networks:
  ros:
    driver: bridge

services:
  ros-master:
    image: ros:ros-kinetic-base
    container_name: ros-master
    networks:
      - ros
    privileged: true
    volumes:
      -/dev:/dev
    command:
      - roscore
  
  realsense:
    build: docker
    container_name: realsense
    privileged: true
    networks:
      - ros
    depends_on:
      - ros-master
    environment:
      - "ROS_MASTER_URI=http://ros-master:11311"
      - "ROS_HOSTNAME=realsense"
    volumes:
      -/dev:/dev
    command: roslaunch realsense2_camera rs_rgbd.launch
      # enable_pointcloud:=true \
      # align_depth:=false \
      # depth_registered_processing:=true \
      # align_depth:=true
    restart: always
