version: '3'

services:
  #ros-master:
   # build: docker
   # container_name: ros-master
   # network_mode: host
   # privileged: true
   # volumes:
   #   - /dev:/dev
   # command:
    #  - roscore
  
  realsense:
    build: docker
    container_name: realsense
    privileged: true
    network_mode: host
    #depends_on:
    #  - ros-master
    volumes:
      - /dev:/dev
    command: roslaunch realsense2_camera rs_rgbd.launch initial_reset:=true
      # enable_pointcloud:=true \
      # align_depth:=false \
      # depth_registered_processing:=true \
      # align_depth:=true
    # restart: always
