version: '3.7'

services:
  ros-master:
    image: yuxianggao/ros-master:${DOCKER_ROS_DISTRO}-${DOCKER_ARCH}
    build:
      context: dockers/ros-master
      args:
        ROS_DISTRO: "$DOCKER_ROS_DISTRO"
        # ARCH: "$DOCKER_ARCH"
    container_name: ros-master
    network_mode: "host"
    privileged: true
    # Map volumes to sync time with the host
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    restart: always

  ros-realsense:
    image: yuxianggao/ros-realsense:${DOCKER_ROS_DISTRO}-${DOCKER_ARCH}
    build:
      context: dockers/ros-realsense
      args:
        ROS_DISTRO: "$DOCKER_ROS_DISTRO"
        # ARCH: "$DOCKER_ARCH"
    container_name: ros-realsense
    privileged: true
    depends_on:
      - ros-master
    network_mode: "host"
    command: /bin/bash -c "roslaunch --wait realsense2_camera rs_rgbd.launch initial_reset:=true"
    restart: unless-stopped

  ros-gui:
    image: yuxianggao/ros-gui:${DOCKER_ROS_DISTRO}-${DOCKER_ARCH}
    build:
      context: dockers/ros-gui
      args:
        ROS_DISTRO: "$DOCKER_ROS_DISTRO"
        # ARCH: "$DOCKER_ARCH"
    container_name: ros-gui
    network_mode: "host"
    privileged: true
    depends_on:
      - ros-realsense
    volumes:
      #- /dev
      #- /etc/group:/etc/group:ro
      #- /etc/passwd:/etc/passwd:ro
      #- /etc/shadow:/etc/shadow:ro
      #- /etc/sudoers.d:/etc/sudoers.d:ro
      # xhost +local:root
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - $HOME/.Xauthority:/root/.Xauthority:rw
    environment:
      - "DISPLAY"
    command: /bin/bash -c "rqt"
    restart: unless-stopped

  ros-dnn:
    image: yuxianggao/ros-dnn:${DOCKER_ROS_DISTRO}-${DOCKER_ARCH}
    build:
      context: dockers/ros-dnn
      args:
        ROS_DISTRO: "$DOCKER_ROS_DISTRO"
        # ARCH: "$DOCKER_ARCH"
    container_name: ros-dnn
    network_mode: "host"
    privileged: true
    depends_on:
      - ros-realsense
    command: /bin/bash -c "roslaunch --wait dnn_detect dnn_detect.launch camera:=/camera/color image:=image_raw"
    restart: unless-stopped
